[package]
name = "game-2048"
version = "0.1.0"
authors = ["Adrien Ball <adrien.ball@snips.ai>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
lazy_static = "1.4.0"
fnv = "1.0.6"
env_logger = "0.7.1"
clap = "2.33.0"
log = "0.4.8"
termion = "1.5.3"
